<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
?>
<html>
<head>
    <?=
    $this->headLink(['rel' => 'preload', 'href' => '/style/foo.css'])
        ->headLink(['rel' => 'prefetch', 'href' => '/style/bar.css', 'as' => 'style', 'type' => 'text/stylesheet'])
        ->appendStylesheet('/style/stylesheet.css')
    ?>
    <?=
    $this->headScript()
        ->appendFile('/script/foo.js')
        ->appendFile('/script/bar.js', 'text/text')
    ?>
</head>
<body>
<?= $this->content ?>
</body>
</html>